### ISSUE TITLE
which not finding netstat and traceroute

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/whichport#4]
bash-5.2$ which netstat
which: no netstat

bash-5.2$ which traceroute
which: no traceroute

bash-5.2$ netstat | head -n3
MVS TCP/IP NETSTAT CS V2R5       TCPIP Name: TCPIP           16:36:24
User Id  Conn     Local Socket           Foreign Socket         State
-------  ----     ------------           --------------         -----

bash-5.2$ traceroute mvs-sysd | head -n1
CS V2R5: Traceroute to

**Comment by IgorTodorovskiIBM** [comment]
@HarithaIBM , I'd guess that a similar patch as in Bash is needed for which: https://github.com/ZOSOpenTools/bashport/blob/main/stable-patches/findcmd.c.patch#L12

**Comment by HarithaIBM** [comment]
Fixed [here](https://github.com/ZOSOpenTools/whichport/pull/5)

**Comment by gngrossi** [comment]
Looks good...thanks

RC=(0) [SYSA] bash-5.2$ which netstat
/bin/netstat

RC=(0) [SYSA] bash-5.2$ which traceroute
/bin/traceroute
